#!/bin/bash

if [ -z "$1" ]; then
cat <<EOU
Capture some screenshots of surfaces produced by
FreeSurfer in standard orientations.
This version uses freeview.

Usage: takeshots [options]

The options are:
-s <subjid> : Specify one subject ID.
-l <listid> : Specify a file list with the subject IDs, one per line.
-m <mesh>   : Specify a surface file (pial, white, inflated, sphere, etc.).
-p <parc>   : Specify a parcellation to load (aparc, aparc.a2009s, aparc.a2005s).
-c          : Run also for curv.
-u          : Run also for sulc.
-t          : Run also for thickness.
-y          : Run also for myelin maps (require ?h.myelin.mgz exist)
-v          : Run also for volumes (aseg + overlaid surfaces).

_____________________________________
Anderson M. Winkler & Andre Zugman
NIH / NIMH
Oct/2021
http://brainder.org
EOU
exit 1
fi



make_surf_cmd () {
echo "
	freeview -view lateral -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_${hemi}_${m}_${WHAT}_lat.png 2 1
	freeview -view medial -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_${hemi}_${m}_${WHAT}_med.png 2 1
	freeview -view inferior -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_${hemi}_${m}_${WHAT}_inf.png 2 1
	freeview -cam elevation 180 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_${hemi}_${m}_${WHAT}_sup.png 2 1
	exit" > ${SUBJECTS_DIR}/${SUBJECT}/shots/surf.cmd
	}
	 
create_error_surf () {
	convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_${hemi}_${SURF}_${WHAT}_lat.png
	convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_${hemi}_${SURF}_${WHAT}_med.png
	convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_${hemi}_${SURF}_${WHAT}_inf.png
	convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_${hemi}_${SURF}_${WHAT}_sup.png
}
			
DOASEG="N"
DOSURF="Y"
DOCURV="N"
DOSULC="N"
DOTHCK="N"
MESH_LIST="pial white inflated"
PARC_LIST="aparc"

while getopts 's:l:m:p:cutyv' OPTION
do
  case ${OPTION} in
    s) SUBJ_LIST="${SUBJ_LIST} ${OPTARG}" ;;
    l) SUBJ_LIST="${SUBJ_LIST} $(cat ${OPTARG})" ;;
    m) DOSURF="Y" ; MESH_LIST="${MESH_LIST} ${OPTARG}" ;;
    p) DOSURF="Y" ; PARC_LIST="${PARC_LIST} ${OPTARG}" ;;
    c) DOSURF="Y" ; DOCURV="Y" ;;
    u) DOSURF="Y" ; DOSULC="Y" ;;
    t) DOSURF="Y" ; DOTHCK="Y" ;;
    y) DOSURF="Y" ; DOMYEL="Y" ;;
    v) DOASEG="Y" ;; 
  esac
done




#Takeshots for surfaces
if [[ ${DOSURF} == "Y" ]] ; then
	for SUBJECT in ${SUBJ_LIST} ; do
	mkdir -p ${SUBJECTS_DIR}/${SUBJECT}/shots
  		for hemi in lh rh ; do
		    	for m in ${MESH_LIST} ; do
				for p in ${PARC_LIST} ; do
					WHAT=${p}
					if [[ -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m} ]] ; then
						make_surf_cmd
						freeview -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m}:annot=${SUBJECTS_DIR}/${SUBJECT}/label/${hemi}.${WHAT}.annot -cmd ${SUBJECTS_DIR}/${SUBJECT}/shots/surf.cmd -viewport 3d -continue
				 	else
						create_error_surf
					fi
		      		done
				if [[ ${DOCURV} == "Y" ]] ; then
					WHAT=curv
					if [[ -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m} ]] ; then
						make_surf_cmd
						freeview -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m}:overlay=${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${WHAT}:curvature_method=off -cmd ${SUBJECTS_DIR}/${SUBJECT}/shots/surf.cmd -viewport 3d -continue
				 	else
						create_error_surf
					fi				
				fi
				if [[ ${DOSULC} == "Y" ]] ; then
					WHAT=sulc
					if [[ -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m} ]] ; then
						make_surf_cmd
						freeview -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m}:overlay=${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${WHAT}:curvature_method=off -cmd ${SUBJECTS_DIR}/${SUBJECT}/shots/surf.cmd -viewport 3d -continue
					else
						create_error_surf
					fi				

				fi
				if [[ ${DOTHCK} == "Y" ]] ; then
					WHAT=thickness
					if [[ -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m} ]] ; then
						make_surf_cmd
						freeview -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m}:overlay=${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${WHAT}:overlay_threshold=0,4.5:curvature_method=off -cmd ${SUBJECTS_DIR}/${SUBJECT}/shots/surf.cmd -viewport 3d -continue
					else
						create_error_surf
					fi				
				fi
				if [[ ${DOMYEL} == "Y" ]] ; then
					WHAT=myelin
					if [[ -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m} ]] ; then
						make_surf_cmd
						freeview -f ${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${m}:overlay=${SUBJECTS_DIR}/${SUBJECT}/surf/${hemi}.${WHAT}:overlay_threshold=0.5,1.5:curvature_method=off -cmd ${SUBJECTS_DIR}/${SUBJECT}/shots/surf.cmd -viewport 3d -continue
					else
						create_error_surf
					fi					
				fi

			done
		done
	done
fi





# Do for Volume and ASEG
if [[ ${DOASEG} == "Y" ]] ; then
for SUBJECT in ${SUBJ_LIST} ; do
	echo "
	freeview  -viewport coronal -slice 128 128 068 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor068.png 2 1
	freeview  -viewport coronal -slice 128 128 088 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor088.png 2 1
	freeview  -viewport coronal -slice 128 128 098 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor098.png 2 1
	freeview  -viewport coronal -slice 128 128 108 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor108.png 2 1
	freeview  -viewport coronal -slice 128 128 118 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor118.png 2 1
	freeview  -viewport coronal -slice 128 128 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor128.png 2 1
	freeview  -viewport coronal -slice 128 128 138 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor138.png 2 1
	freeview  -viewport coronal -slice 128 128 148 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor148.png 2 1
	freeview  -viewport coronal -slice 128 128 158 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor158.png 2 1
	freeview  -viewport coronal -slice 128 128 168 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor168.png 2 1
	freeview  -viewport coronal -slice 128 128 188 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor188.png 2 1
	freeview  -viewport axial -slice 128 118 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_tra118.png 2 1
	freeview  -viewport axial -slice 128 128 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_tra128.png 2 1
	freeview  -viewport axial -slice 128 138 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_tra138.png 2 1
	freeview  -viewport sagittal -slice 88 118 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_sag088.png 2 1
	freeview  -viewport sagittal -slice 168 118 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_sag168.png 2 1
	exit" > ${SUBJECTS_DIR}/${SUBJECT}/shots/volume.cmd

	if [[ -f ${SUBJECTS_DIR}/${SUBJECT}/mri/brainmask.mgz ]] && [[ -f ${SUBJECTS_DIR}/${SUBJECT}/surf/lh.white ]] && [[ -f ${SUBJECTS_DIR}/${SUBJECT}/surf/rh.white ]] && [[ -f ${SUBJECTS_DIR}/${SUBJECT}/surf/rh.pial ]] ; then
		freeview -v ${SUBJECTS_DIR}/${SUBJECT}/mri/brainmask.mgz -continue \
		-f ${SUBJECTS_DIR}/${SUBJECT}/surf/lh.white:edgecolor='139,0,0' \
		-f ${SUBJECTS_DIR}/${SUBJECT}/surf/rh.white:edgecolor='139,0,0' \
		-f ${SUBJECTS_DIR}/${SUBJECT}/surf/lh.pial \
		-f ${SUBJECTS_DIR}/${SUBJECT}/surf/rh.pial \
		-cmd ${SUBJECTS_DIR}/${SUBJECT}/shots/volume.cmd
	else
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor068.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor088.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor098.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor108.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor118.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor128.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor138.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor148.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor158.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor168.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_cor188.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/{SUBJECT}_surfaces_tra118.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_tra128.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_tra138.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_sag088.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_surfaces_sag168.png

	fi

	echo "
	freeview  -viewport coronal -slice 128 128 068 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor068.png 2 1
	freeview  -viewport coronal -slice 128 128 088 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor088.png 2 1
	freeview  -viewport coronal -slice 128 128 098 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor098.png 2 1
	freeview  -viewport coronal -slice 128 128 108 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor108.png 2 1
	freeview  -viewport coronal -slice 128 128 118 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor118.png 2 1
	freeview  -viewport coronal -slice 128 128 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor128.png 2 1
	freeview  -viewport coronal -slice 128 128 138 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor138.png 2 1
	freeview  -viewport coronal -slice 128 128 148 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor148.png 2 1
	freeview  -viewport coronal -slice 128 128 158 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor158.png 2 1
	freeview  -viewport coronal -slice 128 128 168 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor168.png 2 1
	freeview  -viewport coronal -slice 128 128 188 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor188.png 2 1
	freeview  -viewport axial -slice 128 118 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_tra118.png 2 1
	freeview  -viewport axial -slice 128 128 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_tra128.png 2 1
	freeview  -viewport axial -slice 128 138 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_tra138.png 2 1
	freeview  -viewport sagittal -slice 88 118 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_sag088.png 2 1
	freeview  -viewport sagittal -slice 168 118 128 -nocursor -ss ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_sag168.png 2 1
	exit" > ${SUBJECTS_DIR}/${SUBJECT}/shots/volume.cmd
	if [[ -f ${SUBJECTS_DIR}/${SUBJECT}/mri/brainmask.mgz ]] && [[ -f ${SUBJECTS_DIR}/${SUBJECT}/mri/aparc+aseg.mgz ]] ; then
		freeview -v ${SUBJECTS_DIR}/${SUBJECT}/mri/brainmask.mgz -continue \
		-v ${SUBJECTS_DIR}/${SUBJECT}/mri/aparc+aseg.mgz:lut=${FREESURFER_HOME}/FreeSurferColorLUT.txt:opacity=0.12 \
		-cmd ${SUBJECTS_DIR}/${SUBJECT}/shots/volume.cmd
	else
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor068.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor088.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor098.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor108.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor118.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor128.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor138.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor148.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor158.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor168.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_cor188.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/{SUBJECT}_aseg_tra118.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_tra128.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_tra138.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_sag088.png
		convert -background black -font Arial -size 264x264 -pointsize 12 -gravity center -fill white label:"File does not exist" ${SUBJECTS_DIR}/${SUBJECT}/shots/${SUBJECT}_aseg_sag168.png
	fi
	rm ${SUBJECTS_DIR}/${SUBJECT}/shots/volume.cmd
done
fi